---
title: "cheap dividend kings"
output: html_document
date: '2023-04-09'
---

```{r setup, include=FALSE, warning=FALSE}

library(tidyverse)
library(lubridate)
library(tidyquant)
library(TTR)
library(rvest)
library(broom)

```

```{r error=FALSE, message=FALSE, warning=FALSE}

url <- "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
SP500 <- url %>%
  read_html() %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table[1]') %>%
  html_table()
SP500 <- SP500[[1]]

tickers <- SP500$Symbol

days <- 60

sp_table <- tibble()

for(t in tickers) {

  tryCatch({

  ### Get stock info ###
  stock <- tq_get(t,
                 from = today() - years(20),
                 to = today(),
                 get = "stock.prices") 

  stock <- stock %>%
    select(-c("open":"close")) %>%
    mutate(change_last_60 = ((adjusted - lag(adjusted, days)) / lag(adjusted, days)),
           max_next_60 = rollmax(adjusted, days, fill = NA, align = "left"))
  
  ### Save last date info into variable ###
  last_date <- slice(stock, n())[5] %>%
    as_vector()
  
  stock <- stock %>%
    mutate(success = if_else(max_next_60 >= adjusted * 1.1,1,0),
           rsi = RSI(adjusted))
  
  rsi_last <- tail(stock$rsi,1)

  ### Drop NA's ###
  stock <- stock %>%
    drop_na() %>%
    filter(change_last_60 <= last_date) %>%
    group_by(symbol) %>%
    summarize(n = n(),
              chance = mean(success),
              rsi = rsi_last)


  sp_table <- bind_rows(sp_table, stock) 

  }, error=function(e){})

}

sp_table %>%
  arrange(desc(chance)) %>%
  filter(n >= 30,
         chance >= .9,
         rsi <= 40) %>%
  View()


```


```{r}


tickers <- str_sort(c("DOV",	"GPC",	"PG",	"EMR", "MMM",	"CINF",	"KO",	"JNJ",	"CL",	"ITW",	"HRL",	"SWK",	"FRT",	"SYY",	"GWW",	"BDX",	"PPG",	"TGT",	"ABBV",	"ABT",	"KMB",	"PEP",	"NUE",	"SPGI",	"ADM",	"WMT",	"VFC",	"ED",	"LOW",	"ADP",	"WBA",	"PNR",	"MCD",	"MDT",	"SHW",	"BEN",	"APD",	"AMCR",	"XOM",	"AFL",	"CTAS",	"ATO",	"MKC",	"TROW",	"CAH",	"CLX",	"CVX",	"AOS",	"ECL",	"WST",	"ROP",	"LIN",	"CAT",	"CB",	"EXPD",	"BRO",	"ALB",	"ESS",	"O",	"IBM",	"NEE",	"CHD",	"GD"))

days <- 60

div_table <- tibble()

for(t in tickers) {

  tryCatch({

  ### Get stock info ###
  stock <- tq_get(t,
                 from = today() - years(20),
                 to = today(),
                 get = "stock.prices") 

  stock <- stock %>%
    select(-c("open":"close")) %>%
    mutate(change_last_60 = ((adjusted - lag(adjusted, days)) / lag(adjusted, days)),
           max_next_60 = rollmax(adjusted, days, fill = NA, align = "left"))
  
  ### Save last date info into variable ###
  last_date <- slice(stock, n())[5] %>%
    as_vector()
  
  stock <- stock %>%
    mutate(success = if_else(max_next_60 >= adjusted * 1.05,1,0),
           rsi = RSI(adjusted))
  
  rsi_last <- tail(stock$rsi,1)

  ### Drop NA's ###
  stock <- stock %>%
    drop_na() %>%
    filter(change_last_60 <= last_date) %>%
    group_by(symbol) %>%
    summarize(n = n(),
              chance = mean(success),
              rsi = rsi_last)


  div_table <- bind_rows(div_table, stock) 

  }, error=function(e){})

}

div_table %>%
  arrange(desc(chance)) %>%
  filter(n >= 30,
         chance >= .9,
         rsi <= 40) %>%
  View()
```

```{r}

tickers <- str_sort(c("BTC-USD","ETH-USD"))

days <- 30

cry_table <- tibble()

for(t in tickers) {

  tryCatch({

  ### Get stock info ###
  stock <- tq_get(t,
                 from = today() - years(20),
                 to = today(),
                 get = "stock.prices") 

  stock <- stock %>%
    select(-c("open":"close")) %>%
    mutate(change_last_60 = ((adjusted - lag(adjusted, days)) / lag(adjusted, days)),
           max_next_60 = rollmax(adjusted, days, fill = NA, align = "left"))
  
  ### Save last date info into variable ###
  last_date <- slice(stock, n())[5] %>%
    as_vector()
  
  stock <- stock %>%
    mutate(success = if_else(max_next_60 >= adjusted * 1.1,1,0),
           rsi = RSI(adjusted))
  
  rsi_last <- tail(stock$rsi,1)

  ### Drop NA's ###
  stock <- stock %>%
    drop_na() %>%
    filter(change_last_60 <= last_date) %>%
    group_by(symbol) %>%
    summarize(n = n(),
              chance = mean(success),
              rsi = rsi_last)


  cry_table <- bind_rows(cry_table, stock) 

  }, error=function(e){})

}

cry_table %>%
  arrange(desc(chance)) %>%
  filter(n >= 30,
         chance >= .9,
         rsi <= 40) %>%
  View()
```

